.TH "CImg.display.cpp" 3 "Tue Jan 7 2020" "Version v0.3.0" "CImg.display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CImg.display.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CImg\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPR\fP(value)   ;"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fBdisplay1D2D\fP (CImg< T > image)"
.br
.RI "\fIdisplay image as both 2D map and 1D graphs along x or y axis \fP"
.ti -1c
.RI "template<typename T > void \fBdisplay3D\fP (CImg< T > image, const char *file_o, const float ratioz, const unsigned int di, const char *file_pose_i, const char *file_pose_o, unsigned int rtype, bool color_type)"
.br
.RI "\fIdisplay image as 3D surface \fP"
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PR(value)   ;"

.PP
Definition at line 167 of file CImg\&.display\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "template<typename T > void display1D2D (CImg< T >image)"

.PP
display image as both 2D map and 1D graphs along x or y axis \fBParameters:\fP
.RS 4
\fIimage\fP : image to display 
.RE
.PP

.PP
Definition at line 175 of file CImg\&.display\&.cpp\&.
.SS "template<typename T > void display3D (CImg< T >image, const char *file_o, const floatratioz, const unsigned intdi, const char *file_pose_i, const char *file_pose_o, unsigned intrtype, boolcolor_type)"

.PP
display image as 3D surface \fBParameters:\fP
.RS 4
\fIimage\fP : image to display 
.RE
.PP

.PP
Definition at line 329 of file CImg\&.display\&.cpp\&.
.SS "int main (intargc, char **argv)"
\fBTodo\fP
.RS 4
add doxygen comments for main, within the main and \fBPR()\fP 
.RE
.PP
.PP
pre-processing
.PP
display as image (2D map) and profiles (1D graph)
.PP
display as surface (3D)
.PP
display as 2D map 
.PP
Definition at line 456 of file CImg\&.display\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CImg\&.display from the source code\&.
