.TH "todo" 3 "Tue Jan 7 2020" "Version v0.3.0" "CImg.display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.IP "\fBMember \fBmain\fP (int argc, char **argv)\fP" 1c
add doxygen comments for main, within the main and \fBPR()\fP  
.IP "\fBPage \fBuser guide\fP \fP" 1c
use section (instead of paragraphs) and add table of contents (such as in mainpage)
.PP

