.TH "todo" 3 "2 Dec 2010" "Version v0.3.0" "CImg.display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBMember \fBmain\fP \fP" 1c
add doxygen comments for main, within the main and \fBPR()\fP 
.PP
.PP
 
.IP "\fBPage \fBuser guide\fP \fP" 1c
add screen capture 
.PP
.PP
 
.IP "\fBPage \fBuser guide\fP \fP" 1c
use section (instead of paragraphs) and add table of contents (such as in mainpage)
.PP
.PP

