.TH "user" 3 "13 Apr 2012" "Version v0.3.0" "CImg.display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user \- user guide 
\fBTodo\fP
.RS 4
use section (instead of paragraphs) and add table of contents (such as in mainpage)
.RE
.PP
\fBdifferent type of display for image\fP.RS 4

.RE
.PP
3 types of display in this software: 
.PD 0

.IP "\(bu" 2
2D map (default) 
.IP "\(bu" 2
1D graph (\fC--1D\fP option) 
.IP "\(bu" 2
3D surface (\fC--3D\fP option)
.PP
others display command line options using \fC-h\fP option 
.PP
.nf

 CImg.display : display image as 2D map or/and 1D graph(s) or 3D surface. (Dec  2 2010, 23:35:25)

    -i               image.png                Input image
    --blur           -1                       Variance of gaussian pre-blurring (e.g. --blur 2.0)
    --norm           false                    normalize image between 0 and 255 for 8-bit display (e.g. --norm true)
    --1D             false                    display also profile (i.e. 1D graph with --1D true)
    --3D             false                    display as 3D surface
    -o               0                        Output 3D object
    -z               0.25                     Aspect ratio along z-axis
    -di              10                       Step for isophote skipping
    -pi              0                        Input 3D pose  (e.g. pose.cimg)
    -po              pose.cimg                Output 3D pose (e.g. pose.cimg)
    --render-type    2                        type of rendering (E[0-6], see GUI: render type)
    --color-type     true                     type of surface color: true image color, false constant color
    -h               true                     display this help.

.fi
.PP
.PP
\fB2D map (default)\fP.RS 4
display image as map 
.PP
.nf
   ./CImg.display -i image.PNG

.fi
.PP
 GUI keyboard options: 
.PD 0

.IP "\(bu" 2
\fCCtrl+S\fP: save current view 
.PP
.RE
.PP
\fB1D graph\fP.RS 4
display image as both map and 1D graph(s) (either X axis or Y axis) 
.PP
.nf
   ./CImg.display -i image.PNG --1D

.fi
.PP
 GUI keyboard options: 
.PD 0

.IP "\(bu" 2
\fCc:\fP color 
.IP "\(bu" 2
\fCv:\fP value 
.IP "\(bu" 2
\fCl:\fP luminance 
.IP "\(bu" 2
\fCi:\fP intensity 
.IP "\(bu" 2
\fCCtrl+S\fP: save current view
.PP
GUI mouse options: 
.PD 0

.IP "\(bu" 2
\fCleft\fP button: X axis 
.IP "\(bu" 2
\fCright\fP button: Y axis 
.PP
.RE
.PP
\fB3D surface\fP.RS 4
display image as 3D surface (e.g. Gouraud-shaded or isophotes render) 
.PP
.nf
   ./CImg.display -i image.PNG --3D

.fi
.PP
 GUI keyboard options: 
.PD 0

.IP "\(bu" 2
\fCF:\fP toggle Fullscreen 
.IP "\(bu" 2
\fCQ\fP or ESC: Quit (i.e. exit)
.PP
load or save file: 
.PD 0

.IP "\(bu" 2
\fCS:\fP Save displayed image (i.e. 3D view) 
.IP "\(bu" 2
\fCO:\fP save pOse (i.e. 3D view parameters) 
.IP "\(bu" 2
\fCR:\fP Read pose (i.e. 3D view parameters)
.PP
render type: 
.PD 0

.IP "\(bu" 2
\fCC:\fP color render (image or constant) 
.IP "\(bu" 2
\fCT:\fP poinTs render 
.IP "\(bu" 2
\fCL:\fP Lines render 
.IP "\(bu" 2
\fCA:\fP fAces render 
.IP "\(bu" 2
\fCH:\fP flat-sHaded faces render 
.IP "\(bu" 2
\fCG:\fP Gouraud-shaded faces render 
.IP "\(bu" 2
\fCP:\fP Phong-shaded faces render 
.IP "\(bu" 2
\fCI:\fP Isophotes render 
.IP "\(bu" 2
\fCBackSpace\fP : change rendering type (i.e. decrement type) 
.IP "\(bu" 2
any other key : change rendering type (i.e. increment type)
.PP
GUI mouse options: 
.PD 0

.IP "\(bu" 2
\fCleft\fP button: rotate 
.IP "\(bu" 2
\fCmiddle\fP button: move 
.IP "\(bu" 2
\fCwheel\fP or \fCright\fP button: zoom in/out  
.PP
.RE
.PP

